### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by techmentalist** [SOLAR-group/TAWOS#1]
I really interested in your work, however after building a database scheme in mysql, I cannot find any clue or additional information to retrieve the dataset. It is only the empty database so far.

**Comment by zirock699** [comment]
A bit late answer, but I had the same issue then i found the data set in this website [Link](https://rdr.ucl.ac.uk/articles/dataset/The_TAWOS_dataset/19085834)

**Comment by vtawosi** [comment]
Sorry for the inconvenience! The dataset has gone under some changes and the recent version is accessible from [https://doi.org/10.5522/04/21308124](https://doi.org/10.5522/04/21308124). The link also is provided in Step 2 of the Installation Instructions section.
Hope this helps!
